version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_SECRET: ${APP_SECRET}
      SENTRY_DSN: ${SENTRY_DSN}
      GOOGLE_FONTS_API_KEY: ${GOOGLE_FONTS_API_KEY}

